language: c++

branches:
  only:
    - devel

sudo: required

before_install:
  - wget https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_amd64.deb
  - sudo dpkg -i hugo_0.15_amd64.deb

before_script:
  - cd ${TRAVIS_BUILD_DIR}/..
  - git clone https://gist.github.com/b73112ba396df4b6f1c0a9ac6c122ce5.git gist-deploy
  - cd ${TRAVIS_BUILD_DIR}
  - hugo version
  - mkdir themes
  - git clone --depth 1 https://github.com/aerohub/hugo-identity-theme themes/identity

script:
  - hugo
  - export DEPLOY_DIR=${TRAVIS_BUILD_DIR}/public

after_success:
  - pwd
  - bash ${TRAVIS_BUILD_DIR}/../gist-deploy/deploy_ghpages_master.sh

env:
  global:
    - GIT_EMAIL: travis@example.com
    - secure: ozmRJA0Plth3mdLkdUWXwAdL7JB8oYWK7988sBhUSbgh4AOHASqqGQF6jNvhT9/fjd/mGCXhYeJHuPKz3izKsp5zbUxGYB+FdhEjoxDsBGuc6n/R4AJQIX6/UI/y4LpPjHmwK/OpFnFUt/qEgQxlTBEwZdtThIOYdA9DpkCyBsa45UdteMPjHAGpwwbuPFSH6GxyPJ7kNog1gp+6fERm890tUn48nhKVoFQzAB9H7+iz2OnTvu6XTe07/aG6zkTd6SddZvP3dnoDh96zR1R0NH9n8Ax7B4BLgR4jCRhY/k18bjOYOT0tv3wGP2e1Gw6SpG+rf4yOpQrNksxpQvig67XJceBYejqfAA3ufwtmgY7wb3pW10EgRzO22rp3moSmEjlVV4zU9LntpuzjOYM00S7b463gP6KYcuCFgUtMMGx/yO+ENpn4ciCp0rzkK8rVk6ErMU/7wCBdkLbqWwojVtlPTFr08UwvggUCqIQFAglZs0ozGC4BoorSOzt17IPWUroKGhYxX5gdfwrYXWyjmIbG5QXzyOKXTxBMJp64nIRuFMNlI9ZSVI3JNrZS7r/kXEdQlapU4uqgD1iFkkjvEelTMxAn0mrSXr2qcOo5aAD20uFHSnwoLr13fdDQJYDWGXMpUYRd0Qnlljl/ztpP5Ct4nlwSjo3qnimklfrHp5U=
