language: c++

branches:
  only:
    - devel

sudo: required

before_install:
  - wget https://github.com/spf13/hugo/releases/download/v0.15/hugo_0.15_amd64.deb
  - sudo dpkg -i hugo_0.15_amd64.deb

before_script:
  - cd ${TRAVIS_BUILD_DIR}/..
  - git clone https://gist.github.com/b73112ba396df4b6f1c0a9ac6c122ce5.git gist-deploy
  - cd ${TRAVIS_BUILD_DIR}
  - hugo version
  - mkdir themes
  - git clone --depth 1 https://github.com/aerohub/hugo-identity-theme themes/identity

script:
  - hugo
  - export DEPLOY_DIR=${TRAVIS_BUILD_DIR}/public

after_success:
  - pwd
  - bash ${TRAVIS_BUILD_DIR}/../gist-deploy/deploy_ghpages_master.sh

env:
  global:
    - GIT_EMAIL: travis@example.com
    - secure: oFyelSO7HVNhdbtktLtczHpibWHdw2fdQ1m34MP1GIp+pFjSFFi/W/69Byr5tifcW9PTHCy5gSq39aUqyrz7agj8AT4SbTe9pyIsQ8tOZq1mVS/k8aHLg8m/NguInYpomc8/Umg0X+DB9clrBCu8gh401EALvRyGNOfvNe4iUcrOjWqECTeS5P+ydN3JpdQKsj+n14cPH1wmkS4BEzUO6Ax6GIf9+gH49pcw6CvGCq5p6FvGv+cpllXNd+QTEdF8mVpL74whRO17V7tV25BjupyipobPyCGD1u0KpmKTX2tMbHlmA217fYOclKI5P5Q52sjpml3Th0jjtL1y4gktUH0UdT4GkEB6gjTnb/5T2aYClWFSFet3OqCnrM0Jel18vyIAIL+4n4hidkxC3PAgNq1+JONnmmb8try9xz7jLdRRnHfpEYbu8Rra86LLivAFaSUGWL1DpIOgtnHjiDV6O6znVjA+tFDMx5MBWbXg9AHfjW0+urFHdy9SJLksqLGjL7rMQvOiqS6u0xn2HCM+AjhmYW8uLDrTwb4guRfWdJUcg7hga98eMYPIiW2K2lG1HE9R+WbSCYadNlbbJUR1rMdDoC/UYzbCjEmGfYdDtyJ8GnvXIWa12ttyEHF8pLbr2gt9naMXsa9Jtp5psGe0n463OImOrJKPrbfAq7DwqIE=
