baseurl = "http://moos-ivp.github.io"
languageCode = "en-us"
title = "MOOS-IvP on Github"
theme = "identity"

[params]

	# Images settings
	# Icons, backgrounds and avatars folders are placed in theme's static/images folder.
	# You may place your images in corresponding folders and then set only filenames below to
	# change page's appearance

	favicon = "favicon2.ico"
	appletouchicon = "apple-touch-icon-precomposed.png"
	background = "bg1.jpg"
	avatar = "head.jpg"

	# Personal settings

  name = "MOOS-IvP"
	position = "Open-source Marine Autonomy Suite"
  # Social settings
	# You may change these with your social links or add others

	[[params.social]]
		title = "Twitter"
		icon = "fa-twitter"
		link = "https://twitter.com/moosivp"

	[[params.social]]
		title = "Github"
		icon = "fa-github"
		link = "https://github.com/moos-ivp"

	[[params.social]]
		title = "Website"
		icon = "fa-globe"
		link = "http://moos-ivp.org"

	# Footer settings
	[params.footer]
		copyright = "MOOS-IvP"
